# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(300, 275)
        login_window.setMinimumSize(QtCore.QSize(300, 275))
        login_window.setMaximumSize(QtCore.QSize(300, 275))
        self.label_login = QtWidgets.QLabel(login_window)
        self.label_login.setGeometry(QtCore.QRect(0, 50, 67, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(login_window)
        self.label_password.setGeometry(QtCore.QRect(0, 120, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.pushButton_login = QtWidgets.QPushButton(login_window)
        self.pushButton_login.setGeometry(QtCore.QRect(70, 160, 171, 31))
        self.pushButton_login.setStyleSheet("")
        self.pushButton_login.setObjectName("pushButton_login")
        self.pushButton_register = QtWidgets.QPushButton(login_window)
        self.pushButton_register.setGeometry(QtCore.QRect(70, 230, 171, 31))
        self.pushButton_register.setStyleSheet("")
        self.pushButton_register.setObjectName("pushButton_register")
        self.label = QtWidgets.QLabel(login_window)
        self.label.setGeometry(QtCore.QRect(140, 200, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.headeing = QtWidgets.QLabel(login_window)
        self.headeing.setGeometry(QtCore.QRect(110, 10, 191, 21))
        self.headeing.setObjectName("headeing")
        self.lineEdit_login = QtWidgets.QLineEdit(login_window)
        self.lineEdit_login.setGeometry(QtCore.QRect(60, 50, 231, 21))
        self.lineEdit_login.setStyleSheet("")
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_password = QtWidgets.QLineEdit(login_window)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 110, 231, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Окно авторизации"))
        self.label_login.setText(_translate("login_window", " Логин:"))
        self.label_password.setText(_translate("login_window", "Пароль:"))
        self.pushButton_login.setText(_translate("login_window", "Войти"))
        self.pushButton_register.setText(_translate("login_window", "Зарегистрироваться"))
        self.label.setText(_translate("login_window", "или"))
        self.headeing.setText(_translate("login_window", "Авторизация"))
