# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(431, 364)
        self.label_FIO = QtWidgets.QLabel(RegisterDialog)
        self.label_FIO.setGeometry(QtCore.QRect(110, 50, 31, 16))
        self.label_FIO.setObjectName("label_FIO")
        self.lineEdit_name = QtWidgets.QLineEdit(RegisterDialog)
        self.lineEdit_name.setGeometry(QtCore.QRect(160, 50, 191, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_email = QtWidgets.QLabel(RegisterDialog)
        self.label_email.setGeometry(QtCore.QRect(100, 90, 41, 16))
        self.label_email.setObjectName("label_email")
        self.lineEdit_email = QtWidgets.QLineEdit(RegisterDialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(160, 90, 191, 21))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_password = QtWidgets.QLineEdit(RegisterDialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(160, 130, 191, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_password = QtWidgets.QLabel(RegisterDialog)
        self.label_password.setGeometry(QtCore.QRect(90, 130, 51, 20))
        self.label_password.setObjectName("label_password")
        self.pushButton_register = QtWidgets.QPushButton(RegisterDialog)
        self.pushButton_register.setGeometry(QtCore.QRect(130, 310, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_register.setFont(font)
        self.pushButton_register.setStyleSheet("")
        self.pushButton_register.setObjectName("pushButton_register")
        self.label_login = QtWidgets.QLabel(RegisterDialog)
        self.label_login.setGeometry(QtCore.QRect(100, 10, 41, 16))
        self.label_login.setObjectName("label_login")
        self.lineEdit_username = QtWidgets.QLineEdit(RegisterDialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(160, 10, 191, 21))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_role = QtWidgets.QLabel(RegisterDialog)
        self.label_role.setGeometry(QtCore.QRect(100, 170, 41, 16))
        self.label_role.setObjectName("label_role")
        self.comboBox = QtWidgets.QComboBox(RegisterDialog)
        self.comboBox.setGeometry(QtCore.QRect(160, 170, 191, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_select_photo = QtWidgets.QPushButton(RegisterDialog)
        self.pushButton_select_photo.setGeometry(QtCore.QRect(150, 230, 141, 41))
        self.pushButton_select_photo.setObjectName("pushButton_select_photo")

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Окно регистрации"))
        self.label_FIO.setText(_translate("RegisterDialog", "Имя:"))
        self.label_email.setText(_translate("RegisterDialog", "Почта:"))
        self.label_password.setText(_translate("RegisterDialog", "Пароль:"))
        self.pushButton_register.setText(_translate("RegisterDialog", "Регистрация"))
        self.label_login.setText(_translate("RegisterDialog", "Логин:"))
        self.label_role.setText(_translate("RegisterDialog", "Роль:"))
        self.pushButton_select_photo.setText(_translate("RegisterDialog", "Загрузить фото"))
