# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createTask.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createTask(object):
    def setupUi(self, createTask):
        createTask.setObjectName("createTask")
        createTask.resize(393, 389)
        self.label_info = QtWidgets.QLabel(createTask)
        self.label_info.setGeometry(QtCore.QRect(80, 0, 431, 31))
        self.label_info.setObjectName("label_info")
        self.label_title = QtWidgets.QLabel(createTask)
        self.label_title.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label_title.setObjectName("label_title")
        self.lineEdit_title = QtWidgets.QLineEdit(createTask)
        self.lineEdit_title.setGeometry(QtCore.QRect(110, 30, 251, 21))
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.label_description = QtWidgets.QLabel(createTask)
        self.label_description.setGeometry(QtCore.QRect(10, 80, 91, 21))
        self.label_description.setObjectName("label_description")
        self.lineEdit_description = QtWidgets.QLineEdit(createTask)
        self.lineEdit_description.setGeometry(QtCore.QRect(110, 70, 251, 21))
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.label_status = QtWidgets.QLabel(createTask)
        self.label_status.setGeometry(QtCore.QRect(10, 120, 351, 31))
        self.label_status.setObjectName("label_status")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(createTask)
        self.dateTimeEdit.setGeometry(QtCore.QRect(110, 150, 251, 31))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.calendarWidget_select_date = QtWidgets.QCalendarWidget(createTask)
        self.calendarWidget_select_date.setGeometry(QtCore.QRect(110, 110, 251, 173))
        self.calendarWidget_select_date.setObjectName("calendarWidget_select_date")
        self.label_assignee_to = QtWidgets.QLabel(createTask)
        self.label_assignee_to.setGeometry(QtCore.QRect(0, 290, 101, 21))
        self.label_assignee_to.setObjectName("label_assignee_to")
        self.label_deadline = QtWidgets.QLabel(createTask)
        self.label_deadline.setGeometry(QtCore.QRect(20, 150, 91, 31))
        self.label_deadline.setObjectName("label_deadline")
        self.comboBox_select_assignee = QtWidgets.QComboBox(createTask)
        self.comboBox_select_assignee.setGeometry(QtCore.QRect(110, 290, 251, 26))
        self.comboBox_select_assignee.setObjectName("comboBox_select_assignee")
        self.pushButton_create_task = QtWidgets.QPushButton(createTask)
        self.pushButton_create_task.setGeometry(QtCore.QRect(150, 340, 141, 41))
        self.pushButton_create_task.setObjectName("pushButton_create_task")
        self.pushButton_open_calendar = QtWidgets.QPushButton(createTask)
        self.pushButton_open_calendar.setGeometry(QtCore.QRect(10, 180, 101, 32))
        self.pushButton_open_calendar.setObjectName("pushButton_open_calendar")

        self.retranslateUi(createTask)
        QtCore.QMetaObject.connectSlotsByName(createTask)

    def retranslateUi(self, createTask):
        _translate = QtCore.QCoreApplication.translate
        createTask.setWindowTitle(_translate("createTask", "Создание задачи"))
        self.label_info.setText(_translate("createTask", "Создание задачи в проекте: "))
        self.label_title.setText(_translate("createTask", "Заголовок:"))
        self.label_description.setText(_translate("createTask", "Описание:"))
        self.label_status.setText(_translate("createTask", "Статус задачи: "))
        self.label_assignee_to.setText(_translate("createTask", "Назначить"))
        self.label_deadline.setText(_translate("createTask", "Дедлайн:"))
        self.pushButton_create_task.setText(_translate("createTask", "Создать задачу"))
        self.pushButton_open_calendar.setText(_translate("createTask", "Календарь"))
