# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(277, 250)
        self.label_info = QtWidgets.QLabel(Form)
        self.label_info.setGeometry(QtCore.QRect(70, 0, 161, 31))
        self.label_info.setObjectName("label_info")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_name.setObjectName("label_name")
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setGeometry(QtCore.QRect(100, 50, 161, 21))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_name_2 = QtWidgets.QLabel(Form)
        self.label_name_2.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_name_2.setObjectName("label_name_2")
        self.lineEdit_description = QtWidgets.QLineEdit(Form)
        self.lineEdit_description.setGeometry(QtCore.QRect(100, 90, 161, 21))
        self.lineEdit_description.setObjectName("lineEdit_description")
        self.pushButton_create_project = QtWidgets.QPushButton(Form)
        self.pushButton_create_project.setGeometry(QtCore.QRect(80, 190, 151, 41))
        self.pushButton_create_project.setObjectName("pushButton_create_project")
        self.comboBox_status = QtWidgets.QComboBox(Form)
        self.comboBox_status.setGeometry(QtCore.QRect(100, 130, 161, 26))
        self.comboBox_status.setObjectName("comboBox_status")
        self.label_name_3 = QtWidgets.QLabel(Form)
        self.label_name_3.setGeometry(QtCore.QRect(30, 130, 71, 31))
        self.label_name_3.setObjectName("label_name_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Создание проекта"))
        self.label_info.setText(_translate("Form", "Создание проекта"))
        self.label_name.setText(_translate("Form", "Название:"))
        self.label_name_2.setText(_translate("Form", "Описание:"))
        self.pushButton_create_project.setText(_translate("Form", "Создать проект"))
        self.label_name_3.setText(_translate("Form", "Статус:"))
