# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaskWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(245, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TaskWidget.sizePolicy().hasHeightForWidth())
        TaskWidget.setSizePolicy(sizePolicy)
        TaskWidget.setMinimumSize(QtCore.QSize(245, 150))
        TaskWidget.setMaximumSize(QtCore.QSize(245, 150))
        self.verticalLayoutWidget = QtWidgets.QWidget(TaskWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_title.setWordWrap(True)
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.label_assignee = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_assignee.setWordWrap(True)
        self.label_assignee.setObjectName("label_assignee")
        self.verticalLayout.addWidget(self.label_assignee)
        self.label_priority = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_priority.setWordWrap(True)
        self.label_priority.setObjectName("label_priority")
        self.verticalLayout.addWidget(self.label_priority)
        self.label_deadline = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_deadline.setWordWrap(True)
        self.label_deadline.setObjectName("label_deadline")
        self.verticalLayout.addWidget(self.label_deadline)

        self.retranslateUi(TaskWidget)
        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Задача"))
        self.label_title.setText(_translate("TaskWidget", "Заголовок"))
        self.label_assignee.setText(_translate("TaskWidget", "Разработчик"))
        self.label_priority.setText(_translate("TaskWidget", "Проритет"))
        self.label_deadline.setText(_translate("TaskWidget", "Дедлайн"))
