# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(350, 330)
        Form.setMinimumSize(QtCore.QSize(350, 330))
        Form.setMaximumSize(QtCore.QSize(350, 330))
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(20, 20, 101, 31))
        self.pushButton_exit.setStyleSheet("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_name = QtWidgets.QLabel(Form)
        self.label_name.setGeometry(QtCore.QRect(70, 90, 41, 16))
        self.label_name.setObjectName("label_name")
        self.label_phone = QtWidgets.QLabel(Form)
        self.label_phone.setGeometry(QtCore.QRect(50, 190, 61, 16))
        self.label_phone.setObjectName("label_phone")
        self.pushButton_update_profile = QtWidgets.QPushButton(Form)
        self.pushButton_update_profile.setGeometry(QtCore.QRect(100, 280, 191, 41))
        self.pushButton_update_profile.setStyleSheet("")
        self.pushButton_update_profile.setObjectName("pushButton_update_profile")
        self.label_name_2 = QtWidgets.QLabel(Form)
        self.label_name_2.setGeometry(QtCore.QRect(60, 140, 51, 20))
        self.label_name_2.setObjectName("label_name_2")
        self.lineEdit_FIO = QtWidgets.QLineEdit(Form)
        self.lineEdit_FIO.setGeometry(QtCore.QRect(110, 80, 231, 21))
        self.lineEdit_FIO.setObjectName("lineEdit_FIO")
        self.lineEdit_email = QtWidgets.QLineEdit(Form)
        self.lineEdit_email.setGeometry(QtCore.QRect(110, 130, 231, 21))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        self.lineEdit_password.setGeometry(QtCore.QRect(110, 180, 231, 21))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_select_photo = QtWidgets.QPushButton(Form)
        self.pushButton_select_photo.setGeometry(QtCore.QRect(120, 220, 131, 32))
        self.pushButton_select_photo.setObjectName("pushButton_select_photo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование профиля"))
        self.pushButton_exit.setText(_translate("Form", "Выйти"))
        self.label_name.setText(_translate("Form", "ФИО:"))
        self.label_phone.setText(_translate("Form", "Пароль:"))
        self.pushButton_update_profile.setText(_translate("Form", "Сохранить изменения"))
        self.label_name_2.setText(_translate("Form", "Почта:"))
        self.pushButton_select_photo.setText(_translate("Form", "Загрузить фото"))
