# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TasksWidget(object):
    def setupUi(self, TasksWidget):
        TasksWidget.setObjectName("TasksWidget")
        TasksWidget.resize(703, 801)
        self.horizontalLayoutWidget = QtWidgets.QWidget(TasksWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 621, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_apply_filters = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_apply_filters.setObjectName("pushButton_apply_filters")
        self.horizontalLayout.addWidget(self.pushButton_apply_filters)
        self.pushButton_reset_filters = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_reset_filters.setObjectName("pushButton_reset_filters")
        self.horizontalLayout.addWidget(self.pushButton_reset_filters)
        self.tableView_tasks = QtWidgets.QTableView(TasksWidget)
        self.tableView_tasks.setGeometry(QtCore.QRect(10, 130, 621, 192))
        self.tableView_tasks.setObjectName("tableView_tasks")
        self.pushButton_exit = QtWidgets.QPushButton(TasksWidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(550, 10, 83, 32))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.groupBox_task_history = QtWidgets.QGroupBox(TasksWidget)
        self.groupBox_task_history.setGeometry(QtCore.QRect(10, 440, 611, 341))
        self.groupBox_task_history.setObjectName("groupBox_task_history")
        self.tableView_tasks_history = QtWidgets.QTableView(self.groupBox_task_history)
        self.tableView_tasks_history.setGeometry(QtCore.QRect(0, 40, 611, 301))
        self.tableView_tasks_history.setObjectName("tableView_tasks_history")
        self.label_current_project = QtWidgets.QLabel(TasksWidget)
        self.label_current_project.setGeometry(QtCore.QRect(20, 0, 281, 31))
        self.label_current_project.setObjectName("label_current_project")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(TasksWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 329, 621, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_buttons_actions = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_buttons_actions.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_buttons_actions.setObjectName("horizontalLayout_buttons_actions")
        self.pushButton_read_task = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_read_task.setObjectName("pushButton_read_task")
        self.horizontalLayout_buttons_actions.addWidget(self.pushButton_read_task)
        self.pushButton_update_status_task = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_update_status_task.setObjectName("pushButton_update_status_task")
        self.horizontalLayout_buttons_actions.addWidget(self.pushButton_update_status_task)
        self.pushButton_reassign_task = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_reassign_task.setObjectName("pushButton_reassign_task")
        self.horizontalLayout_buttons_actions.addWidget(self.pushButton_reassign_task)
        self.pushButton_delete_task = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_delete_task.setObjectName("pushButton_delete_task")
        self.horizontalLayout_buttons_actions.addWidget(self.pushButton_delete_task)
        self.label_task_description = QtWidgets.QLabel(TasksWidget)
        self.label_task_description.setGeometry(QtCore.QRect(10, 380, 611, 61))
        self.label_task_description.setWordWrap(True)
        self.label_task_description.setObjectName("label_task_description")

        self.retranslateUi(TasksWidget)
        QtCore.QMetaObject.connectSlotsByName(TasksWidget)

    def retranslateUi(self, TasksWidget):
        _translate = QtCore.QCoreApplication.translate
        TasksWidget.setWindowTitle(_translate("TasksWidget", "Задачи"))
        self.label.setText(_translate("TasksWidget", "Поиск по задачам"))
        self.pushButton_apply_filters.setText(_translate("TasksWidget", "Применить"))
        self.pushButton_reset_filters.setText(_translate("TasksWidget", "Сбросить"))
        self.pushButton_exit.setText(_translate("TasksWidget", "Выйти"))
        self.groupBox_task_history.setTitle(_translate("TasksWidget", "История задачи"))
        self.label_current_project.setText(_translate("TasksWidget", "TextLabel"))
        self.pushButton_read_task.setText(_translate("TasksWidget", "Подробнее"))
        self.pushButton_update_status_task.setText(_translate("TasksWidget", "Обновить статус"))
        self.pushButton_reassign_task.setText(_translate("TasksWidget", "Переназначить"))
        self.pushButton_delete_task.setText(_translate("TasksWidget", "Удалить"))
        self.label_task_description.setText(_translate("TasksWidget", "TextLabel"))
